#################################################################
# Restore URLs, Certificate names, URL and CN groups and the URL# 
#base of a SNS firewall                                         #
#################################################################

# use the embedded categories
CONFIG OBJECT URLGROUP SETBASE base=NETASQ


# Restore the configuration
CONFIG RESTORE list=urlfiltering fwserial=local $FROM_DATA_FILE("backup-URL_web_objects.na")
